joint_inits:
  torso_lift_joint: 0.1687062500000004
  r_upper_arm_roll_joint: 0
  r_shoulder_pan_joint: 0
  r_shoulder_lift_joint: 0
  r_forearm_roll_joint: 0
  r_elbow_flex_joint: -1.1400000000000001
  r_wrist_flex_joint: -1.0499999999999998
  r_wrist_roll_joint: 0
  l_upper_arm_roll_joint: 0
  l_shoulder_pan_joint: 0
  l_shoulder_lift_joint: 0
  l_forearm_roll_joint: 0
  l_elbow_flex_joint: -1.1399999999999995
  l_wrist_flex_joint: -1.0499999999999998
  l_wrist_roll_joint: 0
  head_pan_joint: 0
  head_tilt_joint: 0

use_odom_joints: true

pub_object_marker_array: true

pub_object_tf: true

pub_object_state_array: true

root_frame_id: odom_combined

