hardware_interface:
  sim_control_mode: 0
  joints: &robot_joints
    - torso_lift_joint
    - r_upper_arm_roll_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_forearm_roll_joint
    - r_elbow_flex_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - l_upper_arm_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_forearm_roll_joint
    - l_elbow_flex_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
    - head_pan_joint
    - head_tilt_joint
    - laser_tilt_mount_joint
    - l_gripper_joint
    - r_gripper_joint
    - r_gripper_motor_slider_joint
    - l_gripper_motor_slider_joint
    - l_gripper_motor_screw_joint
    - r_gripper_motor_screw_joint
    - torso_lift_motor_screw_joint
    - bl_caster_rotation_joint  
    - bl_caster_l_wheel_joint  
    - bl_caster_r_wheel_joint  
    - br_caster_rotation_joint  
    - br_caster_l_wheel_joint  
    - br_caster_r_wheel_joint  
    - fl_caster_rotation_joint  
    - fl_caster_l_wheel_joint  
    - fl_caster_r_wheel_joint  
    - fr_caster_rotation_joint  
    - fr_caster_l_wheel_joint  
    - fr_caster_r_wheel_joint  
generic_hw_control_loop:
  loop_hz: &loop_rate 100
  cycle_time_error_threshold: 0.015
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_rate
whole_body_controller: &whole_body_controller
  type: effort_controllers/JointTrajectoryController  
  joints:
    - torso_lift_joint
    - r_upper_arm_roll_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_forearm_roll_joint
    - r_elbow_flex_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - l_upper_arm_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_forearm_roll_joint
    - l_elbow_flex_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
    - head_pan_joint
    - head_tilt_joint
  gains:
    torso_lift_joint: {p: 20000, i: 1000, d: 500}
    r_upper_arm_roll_joint: {p: 2000, i: 100, d: 50}
    r_shoulder_pan_joint: {p: 2000, i: 100, d: 50}
    r_shoulder_lift_joint: {p: 2000, i: 100, d: 50}
    r_forearm_roll_joint: {p: 2000, i: 100, d: 50}
    r_elbow_flex_joint: {p: 2000, i: 100, d: 50}
    r_wrist_flex_joint: {p: 2000, i: 100, d: 50}
    r_wrist_roll_joint: {p: 2000, i: 100, d: 50}
    l_upper_arm_roll_joint: {p: 2000, i: 100, d: 50}
    l_shoulder_pan_joint: {p: 2000, i: 100, d: 50}
    l_shoulder_lift_joint: {p: 2000, i: 100, d: 50}
    l_forearm_roll_joint: {p: 2000, i: 100, d: 50}
    l_elbow_flex_joint: {p: 2000, i: 100, d: 50}
    l_wrist_flex_joint: {p: 2000, i: 100, d: 50}
    l_wrist_roll_joint: {p: 2000, i: 100, d: 50}
    head_pan_joint: {p: 2000, i: 100, d: 50}
    head_tilt_joint: {p: 2000, i: 100, d: 50}
  constraints:
    torso_lift_joint:
      goal: 0.1
      trajectory: 0.1
    stopped_velocity_tolerance: 0.001
whole_body_controller/body: *whole_body_controller
joint_group_pos_controller:
   type: position_controllers/JointGroupPositionController
   joints:     
    - torso_lift_joint
    - head_pan_joint
    - head_tilt_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_forearm_roll_joint
    - r_elbow_flex_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_forearm_roll_joint
    - l_elbow_flex_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
