joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_rate 500

whole_body_controller: &whole_body_controller
  type: effort_controllers/JointTrajectoryController  
  joints: &joints
    - torso_lift_joint
    - r_upper_arm_roll_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_forearm_roll_joint
    - r_elbow_flex_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - l_upper_arm_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_forearm_roll_joint
    - l_elbow_flex_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
    - head_pan_joint
    - head_tilt_joint
  gains:
    torso_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_upper_arm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_shoulder_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_shoulder_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_forearm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_elbow_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_wrist_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_wrist_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_upper_arm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_shoulder_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_shoulder_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_forearm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_elbow_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_wrist_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_wrist_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    head_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    head_tilt_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
  constraints:
    stopped_velocity_tolerance: 0

# real time controllers
real_time_position_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - torso_lift_joint
    - r_upper_arm_roll_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_forearm_roll_joint
    - r_elbow_flex_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - l_upper_arm_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_forearm_roll_joint
    - l_elbow_flex_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
    - head_pan_joint
    - head_tilt_joint
    - l_gripper_l_finger_joint
    - r_gripper_l_finger_joint
  torso_lift_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_upper_arm_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_shoulder_pan_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_shoulder_lift_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_forearm_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_elbow_flex_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_wrist_flex_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_wrist_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_upper_arm_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_shoulder_pan_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_shoulder_lift_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_forearm_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_elbow_flex_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_wrist_flex_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_wrist_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  head_pan_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  head_tilt_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_gripper_l_finger_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_gripper_l_finger_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}

torso_lift_position_controller:
  type: effort_controllers/JointPositionController
  joint: torso_lift_joint
  pid: { p: 2000, i: 100, d: 50 }
r_upper_arm_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_upper_arm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
r_shoulder_pan_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_shoulder_pan_joint
  pid: { p: 2000, i: 100, d: 50 }
r_shoulder_lift_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_shoulder_lift_joint
  pid: { p: 2000, i: 100, d: 50 }
r_forearm_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_forearm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
r_elbow_flex_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_elbow_flex_joint
  pid: { p: 2000, i: 100, d: 50 }
r_wrist_flex_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_wrist_flex_joint
  pid: { p: 2000, i: 100, d: 50 }
r_wrist_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_wrist_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
l_upper_arm_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_upper_arm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
l_shoulder_pan_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_shoulder_pan_joint
  pid: { p: 2000, i: 100, d: 50 }
l_shoulder_lift_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_shoulder_lift_joint
  pid: { p: 2000, i: 100, d: 50 }
l_forearm_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_forearm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
l_elbow_flex_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_elbow_flex_joint
  pid: { p: 2000, i: 100, d: 50 }
l_wrist_flex_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_wrist_flex_joint
  pid: { p: 2000, i: 100, d: 50 }
l_wrist_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_wrist_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
head_pan_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_pan_joint
  pid: { p: 2000, i: 100, d: 50 }
head_tilt_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_tilt_joint
  pid: { p: 2000, i: 100, d: 50 }

# velocity controllers
vel_gains: &vel_gains
  p: 200.0
  i: 1000.0
  d: 0.1
  i_clamp: 10.0
torso_lift_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: torso_lift_joint
  pid: *vel_gains
r_upper_arm_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_upper_arm_roll_joint
  pid: *vel_gains
r_shoulder_pan_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_shoulder_pan_joint
  pid: *vel_gains
r_shoulder_lift_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_shoulder_lift_joint
  pid: *vel_gains
r_forearm_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_forearm_roll_joint
  pid: *vel_gains
r_elbow_flex_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_elbow_flex_joint
  pid: *vel_gains
r_wrist_flex_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_wrist_flex_joint
  pid: *vel_gains
r_wrist_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_wrist_roll_joint
  pid: *vel_gains
l_upper_arm_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_upper_arm_roll_joint
  pid: *vel_gains
l_shoulder_pan_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_shoulder_pan_joint
  pid: *vel_gains
l_shoulder_lift_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_shoulder_lift_joint
  pid: *vel_gains
l_forearm_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_forearm_roll_joint
  pid: *vel_gains
l_elbow_flex_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_elbow_flex_joint
  pid: *vel_gains
l_wrist_flex_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_wrist_flex_joint
  pid: *vel_gains
l_wrist_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_wrist_roll_joint
  pid: *vel_gains
head_pan_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: head_pan_joint
  pid: *vel_gains
head_tilt_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: head_tilt_joint
  pid: *vel_gains







l_gripper_l_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - l_gripper_l_finger_joint
  gains: 
    l_gripper_l_finger_joint: { p: 2000, i: 100, d: 50 }

r_gripper_l_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - r_gripper_l_finger_joint
  gains: 
    r_gripper_l_finger_joint: { p: 2000, i: 100, d: 50 }